---
abstract: "Generates a CONTRIBUTING file for KENTNL's distributions."
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Author-KENTNL-CONTRIBUTING
provides:
  Dist::Zilla::Plugin::Author::KENTNL::CONTRIBUTING:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/CONTRIBUTING.pm
    version: '0.001005'
recommends:
  Moose: '2.000'
requires:
  Dist::Zilla::Plugin::GenerateFile::ShareDir: '0.006'
  Dist::Zilla::Util::ConfigDumper: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-CONTRIBUTING/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-CONTRIBUTING
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-CONTRIBUTING.git
version: '0.001005'
